import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
    formatApplicationVersionForDisplay,
    isApplicationReleaseTag,
    isApplicationVersionTimestamp,
} from "@/lib/application-version";

const versionWriterPath = join(
    process.cwd(),
    "scripts/write-application-version.mjs",
);

describe("application version", () => {
    it("recognizes canonical ISO UTC timestamps", () => {
        expect(isApplicationVersionTimestamp("2026-07-18T12:34:56.789Z")).toBe(
            true,
        );
        expect(isApplicationVersionTimestamp("unknown")).toBe(false);
        expect(isApplicationVersionTimestamp("2026-07-18")).toBe(false);
        expect(isApplicationVersionTimestamp(undefined)).toBe(false);
    });

    it("formats the timestamp in the browser local time zone", () => {
        expect(
            formatApplicationVersionForDisplay("2026-07-18T12:34:56.789Z"),
        ).toBe(
            new Intl.DateTimeFormat(undefined, {
                dateStyle: "medium",
                timeStyle: "short",
            }).format(new Date("2026-07-18T12:34:56.789Z")),
        );
    });

    it("validates and formats release tags with their build timestamp", () => {
        expect(isApplicationReleaseTag("v0.1.2")).toBe(true);
        expect(isApplicationReleaseTag("0.1.2")).toBe(false);
        expect(isApplicationReleaseTag("v0.1.2-beta.1")).toBe(false);
        expect(
            formatApplicationVersionForDisplay({
                buildTimestamp: "2026-07-18T12:34:56.789Z",
                releaseTag: "v0.1.2",
            }),
        ).toBe(
            `v0.1.2 · built ${formatApplicationVersionForDisplay("2026-07-18T12:34:56.789Z")}`,
        );
    });

    it("writes generated release and build metadata", async () => {
        const directory = await mkdtemp(join(tmpdir(), "budgeted-version-"));
        const outputPath = join(directory, "application-version.generated.ts");
        const packagePath = join(directory, "package.json");
        const timestamp = "2026-07-18T12:34:56.789Z";

        try {
            await writeFile(
                packagePath,
                JSON.stringify({ name: "budgeted", version: "0.1.2" }),
            );
            execFileSync(process.execPath, [
                versionWriterPath,
                "--timestamp",
                timestamp,
                "--package",
                packagePath,
                "--output",
                outputPath,
            ]);

            await expect(readFile(outputPath, "utf8")).resolves.toBe(
                [
                    "// Generated by the pre-commit hook. Do not edit manually.",
                    "export const GENERATED_APPLICATION_VERSION = {",
                    `    buildTimestamp: ${JSON.stringify(timestamp)},`,
                    '    releaseTag: "v0.1.2",',
                    "} as const;",
                    "",
                ].join("\n"),
            );
        } finally {
            await rm(directory, { force: true, recursive: true });
        }
    });

    it("rejects package versions that cannot identify a stable release", async () => {
        const directory = await mkdtemp(join(tmpdir(), "budgeted-version-"));
        const outputPath = join(directory, "application-version.generated.ts");
        const packagePath = join(directory, "package.json");

        try {
            await writeFile(
                packagePath,
                JSON.stringify({ name: "budgeted", version: "0.1.2-beta.1" }),
            );

            expect(() =>
                execFileSync(process.execPath, [
                    versionWriterPath,
                    "--package",
                    packagePath,
                    "--output",
                    outputPath,
                ]),
            ).toThrow();
        } finally {
            await rm(directory, { force: true, recursive: true });
        }
    });
});
